#Theme Name: Handsomely
#CMS - Jekyll
#Developer- Deenesh Chowdhary
#http://deeneshchowdhary.com
title: "42 will do"
site-description: or the Quest of finding the Answer to the Ultimate Question of Life, The Universe, and Everything
email: son-goku241991@gmail.com
description: "small description about you will take you long"
baseurl: # the subpath of your site, e.g. /blog
url: "Son-GokuJ.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email_username: son-goku241991@gmail.com #Your email address
twitter_username:  #Twitter Username goes here
github_username:  Son-GokuJ #Github Username goes here
facebook_username: #your_username #Facebook Username goes here
your_name: Son-GokuJ #Your Name for About
about_yourself:  # Brief description about yourself
copyright_name: Son-GokuJ #Copyright 
# Build settings
markdown: kramdown
paginate: 5 #Total Number of Post in each Page
gems: [jekyll-paginate, jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
  - typography.html
  - contact.html
